//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Inter_002
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказ.
    /// </summary>
    // *** Start programmer edit section *** (Заказ CustomAttributes)

    // *** End programmer edit section *** (Заказ CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаказE", new string[] {
            "КодЗаказа as \'Код заказа\'",
            "Статус as \'Статус\'",
            "Дата as \'Дата\'",
            "Сумма as \'Сумма\'",
            "Клиент as \'Клиент\'",
            "Клиент.ФИО as \'ФИО\'"})]
    [AssociatedDetailViewAttribute("ЗаказE", "СтрокаЗаказа", "СтрокаЗаказаE", true, "", "Строка заказа", true, new string[] {
            ""})]
    [View("ЗаказL", new string[] {
            "КодЗаказа as \'Код заказа\'",
            "Статус as \'Статус\'",
            "Дата as \'Дата\'",
            "Сумма as \'Сумма\'",
            "Клиент.ФИО as \'ФИО\'"})]
    public class Заказ : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодЗаказа;
        
        private IIS.Inter_002.СостояниеЗаказа fСтатус;
        
        private System.DateTime fДата;
        
        private double fСумма;
        
        private IIS.Inter_002.Клиент fКлиент;
        
        private IIS.Inter_002.DetailArrayOfСтрокаЗаказа fСтрокаЗаказа;
        
        // *** Start programmer edit section *** (Заказ CustomMembers)

        // *** End programmer edit section *** (Заказ CustomMembers)

        
        /// <summary>
        /// КодЗаказа.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.КодЗаказа CustomAttributes)

        // *** End programmer edit section *** (Заказ.КодЗаказа CustomAttributes)
        public virtual int КодЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.КодЗаказа Get start)

                // *** End programmer edit section *** (Заказ.КодЗаказа Get start)
                int result = this.fКодЗаказа;
                // *** Start programmer edit section *** (Заказ.КодЗаказа Get end)

                // *** End programmer edit section *** (Заказ.КодЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.КодЗаказа Set start)

                // *** End programmer edit section *** (Заказ.КодЗаказа Set start)
                this.fКодЗаказа = value;
                // *** Start programmer edit section *** (Заказ.КодЗаказа Set end)

                // *** End programmer edit section *** (Заказ.КодЗаказа Set end)
            }
        }
        
        /// <summary>
        /// Статус.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Статус CustomAttributes)

        // *** End programmer edit section *** (Заказ.Статус CustomAttributes)
        public virtual IIS.Inter_002.СостояниеЗаказа Статус
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Статус Get start)

                // *** End programmer edit section *** (Заказ.Статус Get start)
                IIS.Inter_002.СостояниеЗаказа result = this.fСтатус;
                // *** Start programmer edit section *** (Заказ.Статус Get end)

                // *** End programmer edit section *** (Заказ.Статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Статус Set start)

                // *** End programmer edit section *** (Заказ.Статус Set start)
                this.fСтатус = value;
                // *** Start programmer edit section *** (Заказ.Статус Set end)

                // *** End programmer edit section *** (Заказ.Статус Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Дата CustomAttributes)

        // *** End programmer edit section *** (Заказ.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Дата Get start)

                // *** End programmer edit section *** (Заказ.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Заказ.Дата Get end)

                // *** End programmer edit section *** (Заказ.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Дата Set start)

                // *** End programmer edit section *** (Заказ.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Заказ.Дата Set end)

                // *** End programmer edit section *** (Заказ.Дата Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Сумма CustomAttributes)

        // *** End programmer edit section *** (Заказ.Сумма CustomAttributes)
        public virtual double Сумма
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Сумма Get start)

                // *** End programmer edit section *** (Заказ.Сумма Get start)
                double result = this.fСумма;
                // *** Start programmer edit section *** (Заказ.Сумма Get end)

                // *** End programmer edit section *** (Заказ.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Сумма Set start)

                // *** End programmer edit section *** (Заказ.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (Заказ.Сумма Set end)

                // *** End programmer edit section *** (Заказ.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Клиент CustomAttributes)

        // *** End programmer edit section *** (Заказ.Клиент CustomAttributes)
        [NotNull()]
        public virtual IIS.Inter_002.Клиент Клиент
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Клиент Get start)

                // *** End programmer edit section *** (Заказ.Клиент Get start)
                IIS.Inter_002.Клиент result = this.fКлиент;
                // *** Start programmer edit section *** (Заказ.Клиент Get end)

                // *** End programmer edit section *** (Заказ.Клиент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Клиент Set start)

                // *** End programmer edit section *** (Заказ.Клиент Set start)
                this.fКлиент = value;
                // *** Start programmer edit section *** (Заказ.Клиент Set end)

                // *** End programmer edit section *** (Заказ.Клиент Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.СтрокаЗаказа CustomAttributes)

        // *** End programmer edit section *** (Заказ.СтрокаЗаказа CustomAttributes)
        public virtual IIS.Inter_002.DetailArrayOfСтрокаЗаказа СтрокаЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.СтрокаЗаказа Get start)

                // *** End programmer edit section *** (Заказ.СтрокаЗаказа Get start)
                if ((this.fСтрокаЗаказа == null))
                {
                    this.fСтрокаЗаказа = new IIS.Inter_002.DetailArrayOfСтрокаЗаказа(this);
                }
                IIS.Inter_002.DetailArrayOfСтрокаЗаказа result = this.fСтрокаЗаказа;
                // *** Start programmer edit section *** (Заказ.СтрокаЗаказа Get end)

                // *** End programmer edit section *** (Заказ.СтрокаЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.СтрокаЗаказа Set start)

                // *** End programmer edit section *** (Заказ.СтрокаЗаказа Set start)
                this.fСтрокаЗаказа = value;
                // *** Start programmer edit section *** (Заказ.СтрокаЗаказа Set end)

                // *** End programmer edit section *** (Заказ.СтрокаЗаказа Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаказE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказE", typeof(IIS.Inter_002.Заказ));
                }
            }
            
            /// <summary>
            /// "ЗаказL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказL", typeof(IIS.Inter_002.Заказ));
                }
            }
        }
    }
}
