//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Inter_002
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отчет.
    /// </summary>
    // *** Start programmer edit section *** (Отчет CustomAttributes)

    // *** End programmer edit section *** (Отчет CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтчетE", new string[] {
            "КодОтчета as \'Код отчета\'",
            "Дата as \'Дата\'"})]
    [AssociatedDetailViewAttribute("ОтчетE", "СтрокаОтчета", "СтрокаОтчетаE", true, "", "Строка отчета", true, new string[] {
            ""})]
    [View("ОтчетL", new string[] {
            "КодОтчета as \'Код отчета\'",
            "Дата as \'Дата\'"})]
    public class Отчет : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодОтчета;
        
        private System.DateTime fДата;
        
        private IIS.Inter_002.DetailArrayOfСтрокаОтчета fСтрокаОтчета;
        
        // *** Start programmer edit section *** (Отчет CustomMembers)

        // *** End programmer edit section *** (Отчет CustomMembers)

        
        /// <summary>
        /// КодОтчета.
        /// </summary>
        // *** Start programmer edit section *** (Отчет.КодОтчета CustomAttributes)

        // *** End programmer edit section *** (Отчет.КодОтчета CustomAttributes)
        public virtual int КодОтчета
        {
            get
            {
                // *** Start programmer edit section *** (Отчет.КодОтчета Get start)

                // *** End programmer edit section *** (Отчет.КодОтчета Get start)
                int result = this.fКодОтчета;
                // *** Start programmer edit section *** (Отчет.КодОтчета Get end)

                // *** End programmer edit section *** (Отчет.КодОтчета Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Отчет.КодОтчета Set start)

                // *** End programmer edit section *** (Отчет.КодОтчета Set start)
                this.fКодОтчета = value;
                // *** Start programmer edit section *** (Отчет.КодОтчета Set end)

                // *** End programmer edit section *** (Отчет.КодОтчета Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Отчет.Дата CustomAttributes)

        // *** End programmer edit section *** (Отчет.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Отчет.Дата Get start)

                // *** End programmer edit section *** (Отчет.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Отчет.Дата Get end)

                // *** End programmer edit section *** (Отчет.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Отчет.Дата Set start)

                // *** End programmer edit section *** (Отчет.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Отчет.Дата Set end)

                // *** End programmer edit section *** (Отчет.Дата Set end)
            }
        }
        
        /// <summary>
        /// Отчет.
        /// </summary>
        // *** Start programmer edit section *** (Отчет.СтрокаОтчета CustomAttributes)

        // *** End programmer edit section *** (Отчет.СтрокаОтчета CustomAttributes)
        public virtual IIS.Inter_002.DetailArrayOfСтрокаОтчета СтрокаОтчета
        {
            get
            {
                // *** Start programmer edit section *** (Отчет.СтрокаОтчета Get start)

                // *** End programmer edit section *** (Отчет.СтрокаОтчета Get start)
                if ((this.fСтрокаОтчета == null))
                {
                    this.fСтрокаОтчета = new IIS.Inter_002.DetailArrayOfСтрокаОтчета(this);
                }
                IIS.Inter_002.DetailArrayOfСтрокаОтчета result = this.fСтрокаОтчета;
                // *** Start programmer edit section *** (Отчет.СтрокаОтчета Get end)

                // *** End programmer edit section *** (Отчет.СтрокаОтчета Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Отчет.СтрокаОтчета Set start)

                // *** End programmer edit section *** (Отчет.СтрокаОтчета Set start)
                this.fСтрокаОтчета = value;
                // *** Start programmer edit section *** (Отчет.СтрокаОтчета Set end)

                // *** End programmer edit section *** (Отчет.СтрокаОтчета Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтчетE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтчетE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтчетE", typeof(IIS.Inter_002.Отчет));
                }
            }
            
            /// <summary>
            /// "ОтчетL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтчетL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтчетL", typeof(IIS.Inter_002.Отчет));
                }
            }
        }
    }
}
