//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Inter_002
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Поставка.
    /// </summary>
    // *** Start programmer edit section *** (Поставка CustomAttributes)

    // *** End programmer edit section *** (Поставка CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПоставкаE", new string[] {
            "КодПоставки as \'Код поставки\'",
            "Дата as \'Дата\'"})]
    [AssociatedDetailViewAttribute("ПоставкаE", "СтрокаПоставки", "СтрокаПоставкиE", true, "", "Строка поставки", true, new string[] {
            ""})]
    [View("ПоставкаL", new string[] {
            "КодПоставки as \'Код поставки\'",
            "Дата as \'Дата\'"})]
    public class Поставка : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодПоставки;
        
        private System.DateTime fДата;
        
        private IIS.Inter_002.DetailArrayOfСтрокаПоставки fСтрокаПоставки;
        
        // *** Start programmer edit section *** (Поставка CustomMembers)

        // *** End programmer edit section *** (Поставка CustomMembers)

        
        /// <summary>
        /// КодПоставки.
        /// </summary>
        // *** Start programmer edit section *** (Поставка.КодПоставки CustomAttributes)

        // *** End programmer edit section *** (Поставка.КодПоставки CustomAttributes)
        public virtual int КодПоставки
        {
            get
            {
                // *** Start programmer edit section *** (Поставка.КодПоставки Get start)

                // *** End programmer edit section *** (Поставка.КодПоставки Get start)
                int result = this.fКодПоставки;
                // *** Start programmer edit section *** (Поставка.КодПоставки Get end)

                // *** End programmer edit section *** (Поставка.КодПоставки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Поставка.КодПоставки Set start)

                // *** End programmer edit section *** (Поставка.КодПоставки Set start)
                this.fКодПоставки = value;
                // *** Start programmer edit section *** (Поставка.КодПоставки Set end)

                // *** End programmer edit section *** (Поставка.КодПоставки Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Поставка.Дата CustomAttributes)

        // *** End programmer edit section *** (Поставка.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Поставка.Дата Get start)

                // *** End programmer edit section *** (Поставка.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Поставка.Дата Get end)

                // *** End programmer edit section *** (Поставка.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Поставка.Дата Set start)

                // *** End programmer edit section *** (Поставка.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Поставка.Дата Set end)

                // *** End programmer edit section *** (Поставка.Дата Set end)
            }
        }
        
        /// <summary>
        /// Поставка.
        /// </summary>
        // *** Start programmer edit section *** (Поставка.СтрокаПоставки CustomAttributes)

        // *** End programmer edit section *** (Поставка.СтрокаПоставки CustomAttributes)
        public virtual IIS.Inter_002.DetailArrayOfСтрокаПоставки СтрокаПоставки
        {
            get
            {
                // *** Start programmer edit section *** (Поставка.СтрокаПоставки Get start)

                // *** End programmer edit section *** (Поставка.СтрокаПоставки Get start)
                if ((this.fСтрокаПоставки == null))
                {
                    this.fСтрокаПоставки = new IIS.Inter_002.DetailArrayOfСтрокаПоставки(this);
                }
                IIS.Inter_002.DetailArrayOfСтрокаПоставки result = this.fСтрокаПоставки;
                // *** Start programmer edit section *** (Поставка.СтрокаПоставки Get end)

                // *** End programmer edit section *** (Поставка.СтрокаПоставки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Поставка.СтрокаПоставки Set start)

                // *** End programmer edit section *** (Поставка.СтрокаПоставки Set start)
                this.fСтрокаПоставки = value;
                // *** Start programmer edit section *** (Поставка.СтрокаПоставки Set end)

                // *** End programmer edit section *** (Поставка.СтрокаПоставки Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПоставкаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПоставкаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПоставкаE", typeof(IIS.Inter_002.Поставка));
                }
            }
            
            /// <summary>
            /// "ПоставкаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПоставкаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПоставкаL", typeof(IIS.Inter_002.Поставка));
                }
            }
        }
    }
}
