//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Inter_002
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Посылка.
    /// </summary>
    // *** Start programmer edit section *** (Посылка CustomAttributes)

    // *** End programmer edit section *** (Посылка CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПосылкаE", new string[] {
            "КодПосылки as \'Код посылки\'",
            "Статус as \'Статус\'",
            "ДатаОтправки as \'Дата отправки\'",
            "ДатаПрибытия as \'Дата прибытия\'",
            "Заказ as \'Заказ\'",
            "Заказ.КодЗаказа as \'Код заказа\'"})]
    [View("ПосылкаL", new string[] {
            "КодПосылки as \'Код посылки\'",
            "Статус as \'Статус\'",
            "ДатаОтправки as \'Дата отправки\'",
            "ДатаПрибытия as \'Дата прибытия\'",
            "Заказ.КодЗаказа as \'Код заказа\'"})]
    public class Посылка : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодПосылки;
        
        private IIS.Inter_002.СостояниеПосылки fСтатус;
        
        private System.DateTime fДатаОтправки = System.DateTime.Now;
        
        private System.DateTime fДатаПрибытия;
        
        private IIS.Inter_002.Заказ fЗаказ;
        
        // *** Start programmer edit section *** (Посылка CustomMembers)

        // *** End programmer edit section *** (Посылка CustomMembers)

        
        /// <summary>
        /// КодПосылки.
        /// </summary>
        // *** Start programmer edit section *** (Посылка.КодПосылки CustomAttributes)

        // *** End programmer edit section *** (Посылка.КодПосылки CustomAttributes)
        public virtual int КодПосылки
        {
            get
            {
                // *** Start programmer edit section *** (Посылка.КодПосылки Get start)

                // *** End programmer edit section *** (Посылка.КодПосылки Get start)
                int result = this.fКодПосылки;
                // *** Start programmer edit section *** (Посылка.КодПосылки Get end)

                // *** End programmer edit section *** (Посылка.КодПосылки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Посылка.КодПосылки Set start)

                // *** End programmer edit section *** (Посылка.КодПосылки Set start)
                this.fКодПосылки = value;
                // *** Start programmer edit section *** (Посылка.КодПосылки Set end)

                // *** End programmer edit section *** (Посылка.КодПосылки Set end)
            }
        }
        
        /// <summary>
        /// Статус.
        /// </summary>
        // *** Start programmer edit section *** (Посылка.Статус CustomAttributes)

        // *** End programmer edit section *** (Посылка.Статус CustomAttributes)
        public virtual IIS.Inter_002.СостояниеПосылки Статус
        {
            get
            {
                // *** Start programmer edit section *** (Посылка.Статус Get start)

                // *** End programmer edit section *** (Посылка.Статус Get start)
                IIS.Inter_002.СостояниеПосылки result = this.fСтатус;
                // *** Start programmer edit section *** (Посылка.Статус Get end)

                // *** End programmer edit section *** (Посылка.Статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Посылка.Статус Set start)

                // *** End programmer edit section *** (Посылка.Статус Set start)
                this.fСтатус = value;
                // *** Start programmer edit section *** (Посылка.Статус Set end)

                // *** End programmer edit section *** (Посылка.Статус Set end)
            }
        }
        
        /// <summary>
        /// ДатаОтправки.
        /// </summary>
        // *** Start programmer edit section *** (Посылка.ДатаОтправки CustomAttributes)

        // *** End programmer edit section *** (Посылка.ДатаОтправки CustomAttributes)
        public virtual System.DateTime ДатаОтправки
        {
            get
            {
                // *** Start programmer edit section *** (Посылка.ДатаОтправки Get start)

                // *** End programmer edit section *** (Посылка.ДатаОтправки Get start)
                System.DateTime result = this.fДатаОтправки;
                // *** Start programmer edit section *** (Посылка.ДатаОтправки Get end)

                // *** End programmer edit section *** (Посылка.ДатаОтправки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Посылка.ДатаОтправки Set start)

                // *** End programmer edit section *** (Посылка.ДатаОтправки Set start)
                this.fДатаОтправки = value;
                // *** Start programmer edit section *** (Посылка.ДатаОтправки Set end)

                // *** End programmer edit section *** (Посылка.ДатаОтправки Set end)
            }
        }
        
        /// <summary>
        /// ДатаПрибытия.
        /// </summary>
        // *** Start programmer edit section *** (Посылка.ДатаПрибытия CustomAttributes)

        // *** End programmer edit section *** (Посылка.ДатаПрибытия CustomAttributes)
        public virtual System.DateTime ДатаПрибытия
        {
            get
            {
                // *** Start programmer edit section *** (Посылка.ДатаПрибытия Get start)

                // *** End programmer edit section *** (Посылка.ДатаПрибытия Get start)
                System.DateTime result = this.fДатаПрибытия;
                // *** Start programmer edit section *** (Посылка.ДатаПрибытия Get end)

                // *** End programmer edit section *** (Посылка.ДатаПрибытия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Посылка.ДатаПрибытия Set start)

                // *** End programmer edit section *** (Посылка.ДатаПрибытия Set start)
                this.fДатаПрибытия = value;
                // *** Start programmer edit section *** (Посылка.ДатаПрибытия Set end)

                // *** End programmer edit section *** (Посылка.ДатаПрибытия Set end)
            }
        }
        
        /// <summary>
        /// Посылка.
        /// </summary>
        // *** Start programmer edit section *** (Посылка.Заказ CustomAttributes)

        // *** End programmer edit section *** (Посылка.Заказ CustomAttributes)
        [NotNull()]
        public virtual IIS.Inter_002.Заказ Заказ
        {
            get
            {
                // *** Start programmer edit section *** (Посылка.Заказ Get start)

                // *** End programmer edit section *** (Посылка.Заказ Get start)
                IIS.Inter_002.Заказ result = this.fЗаказ;
                // *** Start programmer edit section *** (Посылка.Заказ Get end)

                // *** End programmer edit section *** (Посылка.Заказ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Посылка.Заказ Set start)

                // *** End programmer edit section *** (Посылка.Заказ Set start)
                this.fЗаказ = value;
                // *** Start programmer edit section *** (Посылка.Заказ Set end)

                // *** End programmer edit section *** (Посылка.Заказ Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПосылкаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПосылкаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПосылкаE", typeof(IIS.Inter_002.Посылка));
                }
            }
            
            /// <summary>
            /// "ПосылкаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПосылкаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПосылкаL", typeof(IIS.Inter_002.Посылка));
                }
            }
        }
    }
}
