//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Inter_002
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состояние заказа.
    /// </summary>
    // *** Start programmer edit section *** (СостояниеЗаказа CustomAttributes)

    // *** End programmer edit section *** (СостояниеЗаказа CustomAttributes)
    public enum СостояниеЗаказа
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (СостояниеЗаказа.Оплачен CustomAttributes)

        // *** End programmer edit section *** (СостояниеЗаказа.Оплачен CustomAttributes)
        Оплачен,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (СостояниеЗаказа.Отменен CustomAttributes)

        // *** End programmer edit section *** (СостояниеЗаказа.Отменен CustomAttributes)
        Отменен,
    }
}
