//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Inter_002
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состояние посылки.
    /// </summary>
    // *** Start programmer edit section *** (СостояниеПосылки CustomAttributes)

    // *** End programmer edit section *** (СостояниеПосылки CustomAttributes)
    public enum СостояниеПосылки
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (СостояниеПосылки.Отправлена CustomAttributes)

        // *** End programmer edit section *** (СостояниеПосылки.Отправлена CustomAttributes)
        Отправлена,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (СостояниеПосылки.Неотправлена CustomAttributes)

        // *** End programmer edit section *** (СостояниеПосылки.Неотправлена CustomAttributes)
        Неотправлена,
    }
}
