//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Inter_002
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Строка отчета.
    /// </summary>
    // *** Start programmer edit section *** (СтрокаОтчета CustomAttributes)

    // *** End programmer edit section *** (СтрокаОтчета CustomAttributes)
    [AutoAltered()]
    [Caption("Строка отчета")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СтрокаОтчетаE", new string[] {
            "Количество as \'Количество\'",
            "Cумма as \'Cумма\'",
            "Товар as \'Товар\'",
            "Товар.Название as \'Название\'"}, Hidden=new string[] {
            "Товар.Название"})]
    [MasterViewDefineAttribute("СтрокаОтчетаE", "Товар", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    public class СтрокаОтчета : ICSSoft.STORMNET.DataObject
    {
        
        private int fКоличество;
        
        private double fCумма;
        
        private IIS.Inter_002.Товар fТовар;
        
        private IIS.Inter_002.Отчет fОтчет;
        
        // *** Start programmer edit section *** (СтрокаОтчета CustomMembers)

        // *** End programmer edit section *** (СтрокаОтчета CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (СтрокаОтчета.Количество CustomAttributes)

        // *** End programmer edit section *** (СтрокаОтчета.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (СтрокаОтчета.Количество Get start)

                // *** End programmer edit section *** (СтрокаОтчета.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (СтрокаОтчета.Количество Get end)

                // *** End programmer edit section *** (СтрокаОтчета.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СтрокаОтчета.Количество Set start)

                // *** End programmer edit section *** (СтрокаОтчета.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (СтрокаОтчета.Количество Set end)

                // *** End programmer edit section *** (СтрокаОтчета.Количество Set end)
            }
        }
        
        /// <summary>
        /// Cумма.
        /// </summary>
        // *** Start programmer edit section *** (СтрокаОтчета.Cумма CustomAttributes)

        // *** End programmer edit section *** (СтрокаОтчета.Cумма CustomAttributes)
        public virtual double Cумма
        {
            get
            {
                // *** Start programmer edit section *** (СтрокаОтчета.Cумма Get start)

                // *** End programmer edit section *** (СтрокаОтчета.Cумма Get start)
                double result = this.fCумма;
                // *** Start programmer edit section *** (СтрокаОтчета.Cумма Get end)

                // *** End programmer edit section *** (СтрокаОтчета.Cумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СтрокаОтчета.Cумма Set start)

                // *** End programmer edit section *** (СтрокаОтчета.Cумма Set start)
                this.fCумма = value;
                // *** Start programmer edit section *** (СтрокаОтчета.Cумма Set end)

                // *** End programmer edit section *** (СтрокаОтчета.Cумма Set end)
            }
        }
        
        /// <summary>
        /// Строка отчета.
        /// </summary>
        // *** Start programmer edit section *** (СтрокаОтчета.Товар CustomAttributes)

        // *** End programmer edit section *** (СтрокаОтчета.Товар CustomAttributes)
        [NotNull()]
        public virtual IIS.Inter_002.Товар Товар
        {
            get
            {
                // *** Start programmer edit section *** (СтрокаОтчета.Товар Get start)

                // *** End programmer edit section *** (СтрокаОтчета.Товар Get start)
                IIS.Inter_002.Товар result = this.fТовар;
                // *** Start programmer edit section *** (СтрокаОтчета.Товар Get end)

                // *** End programmer edit section *** (СтрокаОтчета.Товар Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СтрокаОтчета.Товар Set start)

                // *** End programmer edit section *** (СтрокаОтчета.Товар Set start)
                this.fТовар = value;
                // *** Start programmer edit section *** (СтрокаОтчета.Товар Set end)

                // *** End programmer edit section *** (СтрокаОтчета.Товар Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Inter_002.Отчет.
        /// </summary>
        // *** Start programmer edit section *** (СтрокаОтчета.Отчет CustomAttributes)

        // *** End programmer edit section *** (СтрокаОтчета.Отчет CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.Inter_002.Отчет Отчет
        {
            get
            {
                // *** Start programmer edit section *** (СтрокаОтчета.Отчет Get start)

                // *** End programmer edit section *** (СтрокаОтчета.Отчет Get start)
                IIS.Inter_002.Отчет result = this.fОтчет;
                // *** Start programmer edit section *** (СтрокаОтчета.Отчет Get end)

                // *** End programmer edit section *** (СтрокаОтчета.Отчет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СтрокаОтчета.Отчет Set start)

                // *** End programmer edit section *** (СтрокаОтчета.Отчет Set start)
                this.fОтчет = value;
                // *** Start programmer edit section *** (СтрокаОтчета.Отчет Set end)

                // *** End programmer edit section *** (СтрокаОтчета.Отчет Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СтрокаОтчетаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СтрокаОтчетаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СтрокаОтчетаE", typeof(IIS.Inter_002.СтрокаОтчета));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of СтрокаОтчета.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfСтрокаОтчета CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfСтрокаОтчета CustomAttributes)
    public class DetailArrayOfСтрокаОтчета : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Inter_002.DetailArrayOfСтрокаОтчета members)

        // *** End programmer edit section *** (IIS.Inter_002.DetailArrayOfСтрокаОтчета members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type СтрокаОтчета by index.
        /// </summary>
        /// <summary>
        /// Adds object with type СтрокаОтчета.
        /// </summary>
        public DetailArrayOfСтрокаОтчета(IIS.Inter_002.Отчет fОтчет) : 
                base(typeof(СтрокаОтчета), ((ICSSoft.STORMNET.DataObject)(fОтчет)))
        {
        }
        
        public IIS.Inter_002.СтрокаОтчета this[int index]
        {
            get
            {
                return ((IIS.Inter_002.СтрокаОтчета)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Inter_002.СтрокаОтчета dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
