//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Inter_002
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Строка поставки.
    /// </summary>
    // *** Start programmer edit section *** (СтрокаПоставки CustomAttributes)

    // *** End programmer edit section *** (СтрокаПоставки CustomAttributes)
    [AutoAltered()]
    [Caption("Строка поставки")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СтрокаПоставкиE", new string[] {
            "Количество as \'Количество\'",
            "СуммарнаяСтоимость as \'Суммарная стоимость\'",
            "Товар as \'Товар\'",
            "Товар.Название as \'Название\'"}, Hidden=new string[] {
            "Товар.Название"})]
    [MasterViewDefineAttribute("СтрокаПоставкиE", "Товар", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    public class СтрокаПоставки : ICSSoft.STORMNET.DataObject
    {
        
        private int fКоличество;
        
        private double fСуммарнаяСтоимость;
        
        private IIS.Inter_002.Товар fТовар;
        
        private IIS.Inter_002.Поставка fПоставка;
        
        // *** Start programmer edit section *** (СтрокаПоставки CustomMembers)

        // *** End programmer edit section *** (СтрокаПоставки CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (СтрокаПоставки.Количество CustomAttributes)

        // *** End programmer edit section *** (СтрокаПоставки.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (СтрокаПоставки.Количество Get start)

                // *** End programmer edit section *** (СтрокаПоставки.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (СтрокаПоставки.Количество Get end)

                // *** End programmer edit section *** (СтрокаПоставки.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СтрокаПоставки.Количество Set start)

                // *** End programmer edit section *** (СтрокаПоставки.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (СтрокаПоставки.Количество Set end)

                // *** End programmer edit section *** (СтрокаПоставки.Количество Set end)
            }
        }
        
        /// <summary>
        /// СуммарнаяСтоимость.
        /// </summary>
        // *** Start programmer edit section *** (СтрокаПоставки.СуммарнаяСтоимость CustomAttributes)

        // *** End programmer edit section *** (СтрокаПоставки.СуммарнаяСтоимость CustomAttributes)
        public virtual double СуммарнаяСтоимость
        {
            get
            {
                // *** Start programmer edit section *** (СтрокаПоставки.СуммарнаяСтоимость Get start)

                // *** End programmer edit section *** (СтрокаПоставки.СуммарнаяСтоимость Get start)
                double result = this.fСуммарнаяСтоимость;
                // *** Start programmer edit section *** (СтрокаПоставки.СуммарнаяСтоимость Get end)

                // *** End programmer edit section *** (СтрокаПоставки.СуммарнаяСтоимость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СтрокаПоставки.СуммарнаяСтоимость Set start)

                // *** End programmer edit section *** (СтрокаПоставки.СуммарнаяСтоимость Set start)
                this.fСуммарнаяСтоимость = value;
                // *** Start programmer edit section *** (СтрокаПоставки.СуммарнаяСтоимость Set end)

                // *** End programmer edit section *** (СтрокаПоставки.СуммарнаяСтоимость Set end)
            }
        }
        
        /// <summary>
        /// Строка поставки.
        /// </summary>
        // *** Start programmer edit section *** (СтрокаПоставки.Товар CustomAttributes)

        // *** End programmer edit section *** (СтрокаПоставки.Товар CustomAttributes)
        [NotNull()]
        public virtual IIS.Inter_002.Товар Товар
        {
            get
            {
                // *** Start programmer edit section *** (СтрокаПоставки.Товар Get start)

                // *** End programmer edit section *** (СтрокаПоставки.Товар Get start)
                IIS.Inter_002.Товар result = this.fТовар;
                // *** Start programmer edit section *** (СтрокаПоставки.Товар Get end)

                // *** End programmer edit section *** (СтрокаПоставки.Товар Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СтрокаПоставки.Товар Set start)

                // *** End programmer edit section *** (СтрокаПоставки.Товар Set start)
                this.fТовар = value;
                // *** Start programmer edit section *** (СтрокаПоставки.Товар Set end)

                // *** End programmer edit section *** (СтрокаПоставки.Товар Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Inter_002.Поставка.
        /// </summary>
        // *** Start programmer edit section *** (СтрокаПоставки.Поставка CustomAttributes)

        // *** End programmer edit section *** (СтрокаПоставки.Поставка CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.Inter_002.Поставка Поставка
        {
            get
            {
                // *** Start programmer edit section *** (СтрокаПоставки.Поставка Get start)

                // *** End programmer edit section *** (СтрокаПоставки.Поставка Get start)
                IIS.Inter_002.Поставка result = this.fПоставка;
                // *** Start programmer edit section *** (СтрокаПоставки.Поставка Get end)

                // *** End programmer edit section *** (СтрокаПоставки.Поставка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СтрокаПоставки.Поставка Set start)

                // *** End programmer edit section *** (СтрокаПоставки.Поставка Set start)
                this.fПоставка = value;
                // *** Start programmer edit section *** (СтрокаПоставки.Поставка Set end)

                // *** End programmer edit section *** (СтрокаПоставки.Поставка Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СтрокаПоставкиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СтрокаПоставкиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СтрокаПоставкиE", typeof(IIS.Inter_002.СтрокаПоставки));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of СтрокаПоставки.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfСтрокаПоставки CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfСтрокаПоставки CustomAttributes)
    public class DetailArrayOfСтрокаПоставки : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Inter_002.DetailArrayOfСтрокаПоставки members)

        // *** End programmer edit section *** (IIS.Inter_002.DetailArrayOfСтрокаПоставки members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type СтрокаПоставки by index.
        /// </summary>
        /// <summary>
        /// Adds object with type СтрокаПоставки.
        /// </summary>
        public DetailArrayOfСтрокаПоставки(IIS.Inter_002.Поставка fПоставка) : 
                base(typeof(СтрокаПоставки), ((ICSSoft.STORMNET.DataObject)(fПоставка)))
        {
        }
        
        public IIS.Inter_002.СтрокаПоставки this[int index]
        {
            get
            {
                return ((IIS.Inter_002.СтрокаПоставки)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Inter_002.СтрокаПоставки dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
