//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Inter_002
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Товар.
    /// </summary>
    // *** Start programmer edit section *** (Товар CustomAttributes)

    // *** End programmer edit section *** (Товар CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТоварE", new string[] {
            "КодТовара as \'Код товара\'",
            "Название as \'Название\'",
            "Количество as \'Количество\'",
            "СумарнаяСтоимость as \'Сумарная стоимость\'",
            "Склад as \'Склад\'",
            "Склад.Адрес as \'Адрес\'"})]
    [View("ТоварL", new string[] {
            "КодТовара as \'Код товара\'",
            "Название as \'Название\'",
            "Количество as \'Количество\'",
            "СумарнаяСтоимость as \'Сумарная стоимость\'",
            "Склад.Адрес as \'Адрес\'"})]
    public class Товар : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодТовара;
        
        private string fНазвание;
        
        private int fКоличество;
        
        private double fСумарнаяСтоимость;
        
        private IIS.Inter_002.Склад fСклад;
        
        // *** Start programmer edit section *** (Товар CustomMembers)

        // *** End programmer edit section *** (Товар CustomMembers)

        
        /// <summary>
        /// КодТовара.
        /// </summary>
        // *** Start programmer edit section *** (Товар.КодТовара CustomAttributes)

        // *** End programmer edit section *** (Товар.КодТовара CustomAttributes)
        public virtual int КодТовара
        {
            get
            {
                // *** Start programmer edit section *** (Товар.КодТовара Get start)

                // *** End programmer edit section *** (Товар.КодТовара Get start)
                int result = this.fКодТовара;
                // *** Start programmer edit section *** (Товар.КодТовара Get end)

                // *** End programmer edit section *** (Товар.КодТовара Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.КодТовара Set start)

                // *** End programmer edit section *** (Товар.КодТовара Set start)
                this.fКодТовара = value;
                // *** Start programmer edit section *** (Товар.КодТовара Set end)

                // *** End programmer edit section *** (Товар.КодТовара Set end)
            }
        }
        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Товар.Название CustomAttributes)

        // *** End programmer edit section *** (Товар.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Товар.Название Get start)

                // *** End programmer edit section *** (Товар.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Товар.Название Get end)

                // *** End programmer edit section *** (Товар.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.Название Set start)

                // *** End programmer edit section *** (Товар.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Товар.Название Set end)

                // *** End programmer edit section *** (Товар.Название Set end)
            }
        }
        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (Товар.Количество CustomAttributes)

        // *** End programmer edit section *** (Товар.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (Товар.Количество Get start)

                // *** End programmer edit section *** (Товар.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (Товар.Количество Get end)

                // *** End programmer edit section *** (Товар.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.Количество Set start)

                // *** End programmer edit section *** (Товар.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (Товар.Количество Set end)

                // *** End programmer edit section *** (Товар.Количество Set end)
            }
        }
        
        /// <summary>
        /// СумарнаяСтоимость.
        /// </summary>
        // *** Start programmer edit section *** (Товар.СумарнаяСтоимость CustomAttributes)

        // *** End programmer edit section *** (Товар.СумарнаяСтоимость CustomAttributes)
        public virtual double СумарнаяСтоимость
        {
            get
            {
                // *** Start programmer edit section *** (Товар.СумарнаяСтоимость Get start)

                // *** End programmer edit section *** (Товар.СумарнаяСтоимость Get start)
                double result = this.fСумарнаяСтоимость;
                // *** Start programmer edit section *** (Товар.СумарнаяСтоимость Get end)

                // *** End programmer edit section *** (Товар.СумарнаяСтоимость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.СумарнаяСтоимость Set start)

                // *** End programmer edit section *** (Товар.СумарнаяСтоимость Set start)
                this.fСумарнаяСтоимость = value;
                // *** Start programmer edit section *** (Товар.СумарнаяСтоимость Set end)

                // *** End programmer edit section *** (Товар.СумарнаяСтоимость Set end)
            }
        }
        
        /// <summary>
        /// Товар.
        /// </summary>
        // *** Start programmer edit section *** (Товар.Склад CustomAttributes)

        // *** End programmer edit section *** (Товар.Склад CustomAttributes)
        [NotNull()]
        public virtual IIS.Inter_002.Склад Склад
        {
            get
            {
                // *** Start programmer edit section *** (Товар.Склад Get start)

                // *** End programmer edit section *** (Товар.Склад Get start)
                IIS.Inter_002.Склад result = this.fСклад;
                // *** Start programmer edit section *** (Товар.Склад Get end)

                // *** End programmer edit section *** (Товар.Склад Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.Склад Set start)

                // *** End programmer edit section *** (Товар.Склад Set start)
                this.fСклад = value;
                // *** Start programmer edit section *** (Товар.Склад Set end)

                // *** End programmer edit section *** (Товар.Склад Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТоварE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоварE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоварE", typeof(IIS.Inter_002.Товар));
                }
            }
            
            /// <summary>
            /// "ТоварL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоварL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоварL", typeof(IIS.Inter_002.Товар));
                }
            }
        }
    }
}
